routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function (){
    return view('forms.index');
})->name('home');


Route::resource('forms','FormController');
Route::resource('users','UserController');


Route::get('/echoo',[
    'as' => 'echo.prueba',
    'uses' => 'PruebaController@prueba'
]);

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use App\Abierta;
use App\Cerrada;
use App\Dominio;
use App\Fecha;
use App\ModeloEncuesta;
use App\MPregunta;
use App\MRespuesta;
use App\Numero;
use App\Opcion;
use App\Texto;
use Carbon\Carbon;
use Illuminate\Http\Request;
use PhpParser\Node\Expr\Array_;

class FormController extends Controller
{
    public function index()
    {
        //
    }

    public function create()
    {
        $form = new ModeloEncuesta();
        $form->id = 0;
        $preguntas = [];
        return view('forms.create', ['form' => $form, 'preguntas' => $preguntas]);
    }

    public function store(Request $request)
    {
        if($request['formId'] == 0){
            $modelo_encuesta = new ModeloEncuesta();
            $modelo_encuesta->fecha_inicio = "2018-02-03";
            $modelo_encuesta->fecha_fin = "2018-03-03";
            $modelo_encuesta->cantidad_encuestados = 0;
            $modelo_encuesta->version = 1;
            //$modelo_encuesta->created_at = Carbon::now();
            $modelo_encuesta->usuario_id = 1;
        } else {
            $modelo_encuesta = ModeloEncuesta::find($request['formId']);
        }
        $modelo_encuesta->titulo = $request->titulo_formulario;
        $modelo_encuesta->subtitulo = 'subtitulo';
        $modelo_encuesta->descripcion = $request->descripcion_formulario;
        $modelo_encuesta->objetivo = "objetivo";
        $modelo_encuesta->save();


        $m_pregunta = new MPregunta();
        $m_pregunta->titulo = $request->titulo_pregunta;
        if ($request->required == 'on') {
            $m_pregunta->obligatorio = 1;//obligatorio
        } else {
            $m_pregunta->obligatorio = 0;//no obligarotio
        }
        $m_pregunta->modelo_encuesta_id = $modelo_encuesta->id;
        //$m_pregunta->created_at = Carbon::now();
        $m_pregunta->save();

        //Preguntamos si la PREGUNTA es Cerrada.
        if($request->seleccion == 4 || $request->seleccion == 5){
            //Creamos la respuesta que contenga las opciones cerradas
            $m_respuesta = new MRespuesta();
            $m_respuesta->nombre = 'default';
            //$m_respuesta->created_at = Carbon::now();
            $m_respuesta->tipo = 1; // cerrada
            $m_respuesta->m_pregunta_id = $m_pregunta->id;
            $m_respuesta->save();

            //Se crea el tipo cerrado y si es de unica o multiple
            $cerrada = new Cerrada();
            if ($request->seleccion == 4) {
                $cerrada->tipo = 0; //opcion unica
            } else if($request->seleccion == 5){
                $cerrada->tipo = 1; //opcion multiple
            }
            $cerrada->m_respuesta_id = $m_respuesta->id;
            //$cerrada->created_at = Carbon::now();
            $cerrada->save();

            for($i = 0; $i < count($request->answers); $i++){
                // se guarda las opciones del tipo de pregunta que es
                $opcion = new Opcion();
                $opcion->titulo = $request->answers[$i];
                $opcion->valor = 'default'; //borrar despues
                $opcion->tipo_valor = 0; //saber si es numero, texto, fecha
                //$opcion->created_at = Carbon::now();
                $opcion->cerrada_id = $cerrada->id;
                $opcion->save();
            }

            //preguntamos si existe un tipo de pregunta abierta dentro de una cerrada unica o multiple
            if($request->type != null){
                //creamos la respuesta
                $m_respuesta = new MRespuesta();
                $m_respuesta->nombre = 'default';
                $m_respuesta->tipo = 0; // respuesta abierta
                //$m_respuesta->created_at = Carbon::now();
                $m_respuesta->m_pregunta_id = $m_pregunta->id;
                $m_respuesta->save();

                //creamos el tipo abierto
                $abierta = new Abierta();
                $abierta->m_respuesta_id = $m_respuesta->id;
                //$abierta->created_at = Carbon::now();
                $abierta->save();

                //creamos el dominio de la respuesta
                $dominio = new Dominio();
                $dominio->valor_default = 'default';//borrar luego
                $dominio->tipo = $request->type;
                //$dominio->created_at = Carbon::now();
                $dominio->abierta_id = $abierta->id;
                $dominio->save();

                //creamos el tipo de dominio
                if ($request->type == 1) {
                    //texto
                    $texto = new Texto();
                    $texto->max_longitud = $request->text_max;
                    //$texto->created_at = Carbon::now();
                    $texto->dominio_id = $dominio->id;
                    $texto->save();
                } else if ($request->type == 2) {
                    //numero
                    $numero = new Numero();
                    $numero->min_valor = $request->number_min;
                    $numero->max_valor = $request->number_max;
                    //$numero->created_at = Carbon::now();
                    $numero->dominio_id = $dominio->id;
                    $numero->save();
                } //fecha
                else {
                    $fecha = new Fecha();
                    $fecha->min_fecha = $request->date_min;
                    $fecha->max_fecha = $request->date_max;
                    //$fecha->created_at = Carbon::now();
                    $fecha->dominio_id = $dominio->id;
                    $fecha->save();
                }
            }

        } else if($request->seleccion == 1 || $request->seleccion == 2 || $request->seleccion == 3){
            $m_respuesta = new MRespuesta();
            $m_respuesta->nombre = 'default';
            $m_respuesta->tipo = 0; // respuesta abierta


            $m_respuesta->m_pregunta_id = $m_pregunta->id;
            //$m_respuesta->created_at = Carbon::now();
            $m_respuesta->save();

            $abierta = new Abierta();
            $abierta->m_respuesta_id = $m_respuesta->id;
            //$abierta->created_at = Carbon::now();
            $abierta->save();

            $dominio = new Dominio();
            $dominio->valor_default = 'default';//borrar luego
            $dominio->tipo = $request->seleccion;
            //$dominio->created_at = Carbon::now();
            $dominio->abierta_id = $abierta->id;
            $dominio->save();

            if ($request->seleccion == 1) {
                //texto
                $texto = new Texto();
                $texto->max_longitud = $request->longitud_max;
                $texto->dominio_id = $dominio->id;
                //$texto->created_at = Carbon::now();
                $texto->save();
            } else if ($request->seleccion == 2) {
                //numero
                $numero = new Numero();
                $numero->min_valor = $request->numero_min;
                $numero->max_valor = $request->numero_max;
                $numero->dominio_id = $dominio->id;
                //$numero->created_at = Carbon::now();
                $numero->save();
            } //fecha
            else if($request->seleccion == 3){
                $fecha = new Fecha();
                $fecha->min_fecha = $request->fecha_min;
                $fecha->max_fecha = $request->fecha_max;
                $fecha->dominio_id = $dominio->id;
                //$fecha->created_at = Carbon::now();
                $fecha->save();
            }
        }

        return redirect()->route('forms.show', $modelo_encuesta->id);

    }

    public function show($id){
        $encuesta = ModeloEncuesta::find($id);
        $preguntas = $encuesta->m_preguntas;
        return view('forms.create', ['form' => $encuesta, 'preguntas' => $preguntas]);
    }

    public function edit($id){

    }

    public function update(Request $request, $id){
        //
    }

    public function destroy($id){
        //
    }
}

resources/views/forms/create.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Crear Encuesta</title>

    <!-- Fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway:100,600">

    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="{{asset('css/jqvmap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/flag-icon-css/css/flag-icon.min.css')}}">
    <!-- Materialize-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/admin-materialize.min.css')}}">
    <!-- Material Icons-->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<style>
    .switch label input[type=checkbox]:checked + .lever {
        background-color: #e1bee7 !important;
    }

    .switch label input[type=checkbox]:checked + .lever:before, .switch label input[type=checkbox]:checked + .lever:after {
        left: 18px;
    }

    .switch label input[type=checkbox]:checked + .lever:after {
        background-color: #4a148c !important;
    }
    .switch label .lever:before {
        background-color: rgba(38, 14, 166, 0.15) !important;
    }

    .switch label .lever:after {
        background-color: #F1F1F1 !important;
        -webkit-box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
        box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
    }

    /* label color */
    .input-field label {
        color: #000;
    }
    /* label focus color */
    .input-field input[type=text]:focus + label {
        color: #4a148c !important;
    }
    /* label underline focus color */
    .input-field input[type=text]:focus {
        border-bottom: 1px solid #4a148c !important;
        box-shadow: 0 1px 0 0 #4a148c !important;
    }
    /* valid color */
    .input-field input[type=text].valid {
        border-bottom: 1px solid #000;
        box-shadow: 0 1px 0 0 #000;
    }
    /* invalid color */
    .input-field input[type=text].invalid {
        border-bottom: 1px solid #000;
        box-shadow: 0 1px 0 0 #000;
    }
    /* icon prefix focus color */
    .input-field .prefix.active {
        color: #4a148c !important;
    }

    textarea.materialize-textarea:focus:not([readonly]) {
        border-bottom: 1px solid #4a148c !important;
        -webkit-box-shadow: 0 1px 0 0 #4a148c !important;
        box-shadow: 0 1px 0 0 #4a148c !important;
    }
</style>
<body class="purple lighten-5">
    <header></header>
    <nav class="nav-extended purple darken-3">
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo"><i class="material-icons small">arrow_back</i> Nuevo Fomulario</a>
            <ul class="right hide-on-med-and-down">
                <li><a href="#"><i class="material-icons right">palette</i></a></li>
                <li><a href="#"><i class="material-icons right">settings</i></a></li>
                <li><a class="waves-effect waves-light btn white purple-text text-darken-3">Guardar</a></li>
                <li><a class="waves-effect waves-light btn white purple-text text-darken-3">Guardar y Enviar</a></li>
                <li><a href="#"><i class="material-icons right">more_vert</i></a></li>
            </ul>
        </div>
        <div class="nav-content">
            <div class="row"></div>
            <div class="row"></div>
            <span class="nav-title">Formulario sin título</span>
            <a class="btn-floating btn-large halfway-fab waves-effect waves-light red darken-4 modal-trigger" href="#modal1">
                <i class="material-icons">add</i>
            </a>
        </div>
    </nav>
    <form method="POST" class="form-horizontal" role="form" action="{{route('forms.store')}}">
        {{ csrf_field() }}
        <div style="position: relative; bottom: 3rem">
            <div class="container">
                <div class="row">
                    <div class="col s12 m10 l8 offset-m1 offset-l2">
                        <div class="card-panel">
                            <div class="row">

                                    <div class="row">
                                        <div class="input-field">
                                            <input type="hidden" name="formId" value="{{$form->id}}">
                                        </div>
                                        <div class="input-field col s12">
                                            <input placeholder="Titulo del formulario" id="first_name" type="text" class="validate" name="titulo_formulario" value="{{$form->titulo . $form->id}}" style="font-size: xx-large">
                                        </div>
                                        <div class="input-field col s12">
                                            <textarea class="materialize-textarea" name="descripcion_formulario" placeholder="Descripción del formulario">{{$form->descripcion}}</textarea>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <ul class="collection with-header">
                                            @foreach($preguntas as $pregunta)
                                            <li class="collection-item">
                                                <div>{{$pregunta->titulo}}<a href="#!" class="secondary-content"><i class="material-icons red-text text-darken-4">settings_applications</i></a></div>
                                            </li>
                                            @endforeach

                                        </ul>
                                    </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @include('forms.question')
    </form>

    <!-- Scripts -->
    <script rel="script" type="text/javascript" src="{{asset('js/encuesta.js')}}"></script>
    <script rel="script" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/materialize.js')}}"></script>
    <script rel="script" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.2/moment.min.js"></script>

    <!-- External libraries -->

    <!-- jqvmap -->
    <script rel="script" type="text/javascript" src="{{asset('js/jqvmap/jquery.vmap.min.js')}}"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/jqvmap/jquery.vmap.world.js')}}" charset="utf-8"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/jqvmap/jquery.vmap.sampledata.js')}}"></script>

    <!-- ChartJS -->
    <script rel="script" type="text/javascript" src="{{asset('js/Chart.js')}}"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/Chart.Financial.js')}}"></script>


    <script rel="script" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/fullcalendar.min.js"></script>
    <script rel="script" type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.js"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/imagesloaded.pkgd.min.js')}}"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/masonry.pkgd.min.js')}}"></script>


    <!-- Initialization script -->
    <script rel="script" type="text/javascript" src="{{asset('js/admin.js')}}"></script>
    <script rel="script" type="text/javascript" src="{{asset('js/init.js')}}"></script>

</body>
</html>

resources/views/forms/index.blade.php
@extends('template.app')

@section('container')
    <div class="grey darken-4">
        <div class="container">
            <div class="row">
                <div class="col s6 m3 l3 xl2 offset-s3">
                    <p class="flow-text white-text">Crear Formulario</p>
                    <a href="{{route('forms.create')}}">
                        <div class="card">
                            <div class="card-content">
                                <div class="container">
                                    <img class="responsive-img" src="{{asset('img/svg/add-plus-button.svg')}}" alt="">
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="grey lighten-4">
        <div class="container">
            <div class="row">
                <p style="font-weight: bold">Mis Formularios</p>
            </div>
            <div class="row">
                @for($i = 1; $i <= 8; $i++)
                <div class="col s12 m4 l4 xl3">
                    <div class="card">
                        <div class="card-content red darken-4">
                            <h2 class="white-text bold center-align">E{{$i}}</h2>
                        </div>
                        <div class="card-action">
                            <span style="font-weight: 500">Nombre de la encuesta
                                <a class="dropdown-trigger" href="#" data-target="menu{{$i}}"><i class="material-icons right black-text">more_vert</i></a>
                            </span>
                        </div>
                    </div>
                </div>
                <!-- Dropdown Structure -->
                <ul id="menu{{$i}}" class="dropdown-content">
                    <li><a class="grey-text text-darken-2" href="#!"><i class="material-icons small">text_format</i>Cambiar nombre</a></li>
                    <li><a class="grey-text text-darken-2" href="#!"><i class="material-icons small">folder_open</i>Abrir</a></li>
                    <li class="divider" tabindex="-1"></li>
                    <li><a class="grey-text text-darken-2" href="#!"><i class="material-icons small">delete</i>Eliminar</a></li>
                </ul>
                @endfor
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.dropdown-trigger');
            var instances = M.Dropdown.init(elems, {
                alignment : 'left'
            });
        });
    </script>
@endsection

resources/views/forms/question.blade.php
<div id="modal1" class="modal modal-fixed-footer">
    <form action="">
        <div class="modal-content">
            <div class="row">
                <div class="col s12">
                    <div class="row card-panel" style='padding-top: 0.3rem !important; padding-bottom: 0.3rem !important; margin-left: 0.2%; margin-right: 0.2%'>
                        <div class="input-field col s6">
                            <textarea id="textarea1" class="materialize-textarea" name="titulo_pregunta" placeholder="Pregunta" style="font-size: x-large"></textarea>
                        </div>
                        <div class="input-field col s6" style="margin-top: 1.65rem">
                            <select name="seleccion" style="font-size: x-large" onchange="addFieldButton(this.value)">
                                <option value="" disabled selected>Escoja una opción</option>
                                <optgroup label="Respuesta Abierta">
                                    <option value="1" >Respuesta de texto</option>
                                    <option value="2">Respuesta de número</option>
                                    <option value="3" >Respuesta de fecha</option>
                                </optgroup>
                                <optgroup label="Respuesta Cerrada">
                                    <option value="4">Selección única</option>
                                    <option value="5">Selección multiple</option>
                                </optgroup>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div id="answers" class="col s12">
                            <ul id="questions_list">

                            </ul>
                            <div id="other">

                            </div>
                            <div id="field_buttons">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer switch">
            <label class="left-align">
                Obligatorio
                <input type="checkbox" name="required">
                <span class="lever"></span>
            </label>
            <button type="submit" class="modal-close waves-effect waves-red btn red darken-4">Agregar</button>
        </div>
    </form>

    <script>

    </script>
</div>